apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eas5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-eas5@sha256:fdefaa8a3b064cfbdeebf80e7dab11e189c0e0fbdef7e6170d3eabfa152d7c65
        name: my-nodejs
        resources: {}
status: {}
